import Head from 'next/head'
import Header from '@/components/Header'
import { Inter } from '@next/font/google'
import TopCards from '@/components/TopCards'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gray-100 min-h-screen'>
      <Header />
      <TopCards />
      
      </main>
    </>
  )
}
